# Generated by Django 3.1.7 on 2021-05-06 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cuit', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PrismaApp.usuario')),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
            },
            bases=('PrismaApp.usuario',),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PrismaApp.usuario')),
            ],
            options={
                'verbose_name': 'administrativo',
                'verbose_name_plural': 'administrativos',
            },
            bases=('PrismaApp.usuario',),
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PrismaApp.usuario')),
            ],
            options={
                'verbose_name': 'gerente',
                'verbose_name_plural': 'gerentes',
            },
            bases=('PrismaApp.usuario',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PrismaApp.usuario')),
            ],
            options={
                'verbose_name': 'supervisor',
                'verbose_name_plural': 'supervisores',
            },
            bases=('PrismaApp.usuario',),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PrismaApp.usuario')),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
            },
            bases=('PrismaApp.usuario',),
        ),
    ]
