# Generated by Django 3.1.7 on 2021-05-06 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrismaApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amigo',
        ),
    ]
