# Generated by Django 3.1.7 on 2021-05-06 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrismaApp', '0002_delete_amigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativo',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='usuario_ptr',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Administrativo',
        ),
        migrations.DeleteModel(
            name='Gerente',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
