# Generated by Django 3.1.7 on 2021-05-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrismaApp', '0004_auto_20210506_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='Nombre de usuario')),
                ('cuit', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Cuit')),
                ('rol', models.CharField(max_length=30, verbose_name='Rol')),
                ('nombre', models.CharField(blank=True, max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
