# Generated by Django 3.1.7 on 2021-05-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrismaApp', '0005_auto_20210506_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cuit',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Cuit'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
