# Generated by Django 3.1.7 on 2021-05-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrismaApp', '0006_auto_20210506_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_administrador',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
