# Generated by Django 3.1.7 on 2021-05-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrismaApp', '0007_auto_20210506_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_staff',
            new_name='usuario_administrador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
    ]
