# Generated by Django 3.1.7 on 2021-05-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=55, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=15, unique=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción')),
                ('stockminimo', models.IntegerField(default=0, verbose_name='Stock Minimo')),
                ('stockseguridad', models.IntegerField(default=1, verbose_name='Stock de Seguridad')),
                ('ubicacion', models.CharField(max_length=15, verbose_name='Ubicación')),
                ('ultima_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Ultima Modificación')),
                ('repo_por_lote', models.BooleanField(verbose_name='Reposición por Lote')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('solicitud', models.BooleanField(default=False)),
                ('reintentos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad_de_medida', models.CharField(max_length=10, unique=True, verbose_name='tipo_de_unidad')),
            ],
            options={
                'verbose_name': 'unidad_de_medida',
                'verbose_name_plural': 'unidades_de_medida',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('nombre_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.categoria')),
            ],
            options={
                'verbose_name': 'subcategoria',
                'verbose_name_plural': 'subcategorias',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('solicitado', models.IntegerField(default=5, verbose_name='Solicitado 5')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
    ]
