# Generated by Django 3.1.7 on 2021-05-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=36, verbose_name='Solicitado 36'),
        ),
    ]
