# Generated by Django 3.1.7 on 2021-05-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('sucursal', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal'),
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.categoria'),
        ),
        migrations.AddField(
            model_name='item',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.estado'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.subcategoria'),
        ),
        migrations.AddField(
            model_name='item',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal'),
        ),
        migrations.AddField(
            model_name='item',
            name='unidad_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.unidaddemedida'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='prov_preferido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor'),
        ),
    ]
