# Generated by Django 3.1.7 on 2021-06-13 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('item', '0001_initial'),
        ('usuario', '0001_initial'),
        ('sucursal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportepreciositems',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.supervisor'),
        ),
        migrations.AddField(
            model_name='reporteprecios',
            name='categoria_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.categoria'),
        ),
        migrations.AddField(
            model_name='reporteprecios',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.supervisor'),
        ),
        migrations.AddField(
            model_name='reporteprecios',
            name='responsable_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsable_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pinturausada',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal'),
        ),
        migrations.AddField(
            model_name='pinturanueva',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cuenta_corriente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.cuentacorrienteproveedor'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal'),
        ),
        migrations.AddField(
            model_name='mezclausada',
            name='primera_pintura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='item.pinturausada'),
        ),
        migrations.AddField(
            model_name='mezclausada',
            name='segunda_pintura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.pinturausada'),
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.categoria'),
        ),
        migrations.AddField(
            model_name='item',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.estado'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.subcategoria'),
        ),
        migrations.AddField(
            model_name='item',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal'),
        ),
        migrations.AddField(
            model_name='item',
            name='unidad_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.unidaddemedida'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='prov_preferido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor'),
        ),
        migrations.AddField(
            model_name='mezcla',
            name='primera_pintura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='item.pintura'),
        ),
        migrations.AddField(
            model_name='mezcla',
            name='segunda_pintura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.pintura'),
        ),
    ]
