# Generated by Django 3.1.7 on 2021-06-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210606_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinturausada',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=4846783031372, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=46, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='pinturanueva',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=3567791311381, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pinturausada',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=8449268804532, unique=True, verbose_name='Código de barras'),
        ),
    ]
