# Generated by Django 3.1.7 on 2021-05-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210526_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=41, verbose_name='Solicitado 41'),
        ),
    ]
