# Generated by Django 3.1.7 on 2021-06-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210618_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='opciones',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('PENDIENTE', 'Pendiente'), ('DESCONTINUADO', 'Descontinuado')], default='ACTIVO', max_length=13),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=64, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='unidaddemedida',
            name='opciones',
            field=models.CharField(choices=[('TONELADA', 'Tonelada'), ('UNIDAD', 'Unidad'), ('KG', 'Kg'), ('GR', 'Gr'), ('MG', 'Mg'), ('LT', 'Lt'), ('ML', 'Ml'), ('M', 'M'), ('CM', 'Cm'), ('MM', 'Mm')], max_length=8),
        ),
    ]
