# Generated by Django 3.1.7 on 2021-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210522_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=42, verbose_name='Solicitado 42'),
        ),
    ]
