# Generated by Django 3.1.7 on 2021-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210522_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=21, verbose_name='Solicitado 21'),
        ),
    ]
