# Generated by Django 3.1.7 on 2021-06-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210607_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinturausada',
            name='stock',
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=8846577821037, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=51, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='pinturanueva',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=4187260158159, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pinturausada',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=9156551338354, unique=True, verbose_name='Código de barras'),
        ),
        migrations.CreateModel(
            name='MezclaUsada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_primera_pintura', models.PositiveIntegerField(default=0, verbose_name='Cantidad de la primera pintura (En mililitros)')),
                ('cantidad_segunda_pintura', models.PositiveIntegerField(default=0, verbose_name='Cantidad de la segunda pintura (En mililitros)')),
                ('primera_pintura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='item.pinturausada')),
                ('segunda_pintura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.pinturausada')),
            ],
            options={
                'verbose_name': 'mezcla',
                'verbose_name_plural': 'mezclas',
            },
        ),
    ]
