# Generated by Django 3.1.7 on 2021-06-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
        ('item', '0003_auto_20210616_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('proveedor_asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'historial de preferenciados',
                'verbose_name_plural': 'historiales de preferenciados',
            },
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=24, verbose_name='Solicitado '),
        ),
        migrations.DeleteModel(
            name='HistorialPreferenciados',
        ),
    ]
