# Generated by Django 3.1.7 on 2021-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210618_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=29, verbose_name='Solicitado '),
        ),
    ]
