# Generated by Django 3.1.7 on 2021-05-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210526_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=34, verbose_name='Solicitado 34'),
        ),
    ]
