# Generated by Django 3.1.7 on 2021-06-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
        ('item', '0004_auto_20210607_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinturausada',
            name='precio',
            field=models.PositiveIntegerField(default=100, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pinturausada',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=4353785223821, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=60, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='pinturanueva',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=2207929801816, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pinturausada',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=8683242448981, unique=True, verbose_name='Código de barras'),
        ),
    ]
