# Generated by Django 3.1.7 on 2021-05-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20210526_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=68, verbose_name='Solicitado 68'),
        ),
    ]
