# Generated by Django 3.1.7 on 2021-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20210620_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado del pedido'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=31, verbose_name='Solicitado '),
        ),
    ]
