# Generated by Django 3.1.7 on 2021-06-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20210616_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=63, verbose_name='Solicitado '),
        ),
    ]
