# Generated by Django 3.1.7 on 2021-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20210522_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=51, verbose_name='Solicitado 51'),
        ),
    ]
