# Generated by Django 3.1.7 on 2021-06-07 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0005_auto_20210607_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=5794237431788, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=37, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='pinturanueva',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=8043893792989, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pinturausada',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=3768228551160, unique=True, verbose_name='Código de barras'),
        ),
        migrations.CreateModel(
            name='ReportePrecios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio anterior')),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio nuevo')),
                ('item_asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte de precios',
                'verbose_name_plural': 'reportes de precios',
            },
        ),
    ]
