# Generated by Django 3.1.7 on 2021-06-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20210607_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=6176938840572, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=66, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pinturanueva',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=2630177666602, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pinturausada',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=6526370538880, unique=True, verbose_name='Código de barras'),
        ),
    ]
