# Generated by Django 3.1.7 on 2021-06-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20210616_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=75, verbose_name='Solicitado '),
        ),
    ]
