# Generated by Django 3.1.7 on 2021-06-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20210616_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=46, verbose_name='Solicitado '),
        ),
    ]
