# Generated by Django 3.1.7 on 2021-06-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20210621_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=55, verbose_name='Solicitado '),
        ),
    ]
