# Generated by Django 3.1.7 on 2021-06-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20210607_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=6465842497659, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=47, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='pinturanueva',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=4953794040687, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pinturausada',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=3802188603558, unique=True, verbose_name='Código de barras'),
        ),
    ]
