# Generated by Django 3.1.7 on 2021-06-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20210621_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=49, verbose_name='Solicitado '),
        ),
    ]
