# Generated by Django 3.1.7 on 2021-06-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20210607_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteprecios',
            name='item_asociado',
        ),
        migrations.AddField(
            model_name='reporteprecios',
            name='categoria_asociada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='item.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=8909562972856, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=51, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='pinturanueva',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=6986985346601, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pinturausada',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=2894700623454, unique=True, verbose_name='Código de barras'),
        ),
    ]
