# Generated by Django 3.1.7 on 2021-06-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20210608_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=1925082359264, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=66, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='pinturanueva',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=4041425504891, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pinturausada',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=5908518242600, unique=True, verbose_name='Código de barras'),
        ),
    ]
