# Generated by Django 3.1.7 on 2021-06-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20210621_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=31, verbose_name='Solicitado '),
        ),
    ]
