# Generated by Django 3.1.7 on 2021-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_auto_20210622_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=22, verbose_name='Solicitado '),
        ),
    ]
