# Generated by Django 3.1.7 on 2021-06-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_auto_20210608_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporteprecios',
            old_name='precio_anterior',
            new_name='aumento',
        ),
        migrations.RemoveField(
            model_name='reporteprecios',
            name='precio_nuevo',
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=4285871713898, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=32, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='pinturanueva',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=6903591059472, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pinturausada',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=4057766280502, unique=True, verbose_name='Código de barras'),
        ),
    ]
