# Generated by Django 3.1.7 on 2021-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_auto_20210608_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=8974788871319, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=27, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='pinturanueva',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=3764942407823, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='pinturausada',
            name='codigo_de_barras',
            field=models.BigIntegerField(default=1494247688762, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='reporteprecios',
            name='aumento',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Aumento'),
        ),
    ]
