# Generated by Django 3.1.7 on 2021-06-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_auto_20210622_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=34, verbose_name='Solicitado '),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='opciones',
            field=models.CharField(choices=[('Carretillas', 'Carretillas'), ('Andamios', 'Andamios'), ('Elevadores', 'Elevadores'), ('Cerámica', 'Ceramica'), ('Piedra natural', 'Piedra Natural'), ('Perfilería y accesorios', 'Perfileria Y Accesorios'), ('Termostatos', 'Termostatos'), ('Timbres', 'Timbres'), ('Apertura motorizada', 'Apertura Motorizada'), ('Linternas', 'Linternas'), ('Focos', 'Focos'), ('Pantallas', 'Pantallas'), ('Cable', 'Cable'), ('Terminales', 'Terminales'), ('Magnetotérmicos y fusibles', 'Magnetotermicos Y Fusibles'), ('Bombillas led', 'Bombillas Led'), ('Bombillas incandescentes', 'Bombillas Incandescentes'), ('Bombillas bajo consumo', 'Bombillas Bajo Consumo'), ('Hidrolavadores', 'Hidrolavadores'), ('Aspiradores', 'Aspiradores'), ('Compresores', 'Compresores'), ('Motores', 'Motores'), ('Generadores', 'Generadores'), ('Alicates y tenazas', 'Alicates Y Tenazas'), ('Llaves', 'Llaves'), ('Destornilladores', 'Destornilladores'), ('Herramientas de albañilería', 'Herramientas Albanileria'), ('Guantes', 'Guantes'), ('Protección visual', 'Proteccion Visual'), ('Protección auditiva', 'Proteccion Auditiva'), ('Protección anticaidas', 'Proteccion Anticaidas'), ('Cajas y maletas', 'Cajas Y Maletas'), ('Cinturones portaherramientas', 'Cinturones Portaherramientas'), ('Carros', 'Carros'), ('Lavabo pedestal', 'Lavabo Pedestal'), ('Lavamanos', 'Lavamanos'), ('Cisternas', 'Cisternas'), ('Cristal', 'Cristal'), ('Porcelana', 'Porcelana'), ('Madera', 'Madera'), ('Termostáticos', 'Termostaticos'), ('Monobloc', 'Monobloc'), ('Monomando', 'Monomando'), ('Mangueras', 'Mangueras'), ('Difusores', 'Difusores'), ('Regaderas', 'Regaderas'), ('Macetas', 'Macetas'), ('Estanques', 'Estanques'), ('Fuentes', 'Fuentes'), ('Cerraduras para puertas', 'Cerraduras Para Puertas'), ('Sistemas antirrobo', 'Sistemas Antirrobo'), ('Cerraduras electrónicas', 'Cerraduras Electronicas'), ('Interior', 'Interior'), ('Exterior', 'Exterior'), ('Rodillos', 'Rodillos'), ('Pinceles', 'Pinceles'), ('Pilas recargables', 'Pilas Recargables'), ('Pilas no recargables', 'Pilas No Recargables')], max_length=40),
        ),
    ]
