# Generated by Django 3.1.7 on 2021-06-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_auto_20210622_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=54, verbose_name='Solicitado '),
        ),
    ]
