# Generated by Django 3.1.7 on 2021-06-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_auto_20210623_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=36, verbose_name='Solicitado '),
        ),
    ]
