# Generated by Django 3.1.7 on 2021-06-23 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0031_auto_20210623_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpref',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='item.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=61, verbose_name='Solicitado '),
        ),
    ]
