# Generated by Django 3.1.7 on 2021-06-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0032_auto_20210623_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitado',
            field=models.IntegerField(default=65, verbose_name='Solicitado '),
        ),
    ]
