# Generated by Django 3.1.7 on 2021-05-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(blank=True, max_length=11, null=True, verbose_name='Cuit')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('razon_social', models.CharField(blank=True, max_length=40, null=True, verbose_name='Razón Social')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='Correo electronico')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
            },
        ),
    ]
