# Generated by Django 3.1.7 on 2021-05-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(max_length=11, unique=True, verbose_name='Cuit'),
        ),
    ]
