# Generated by Django 3.1.7 on 2021-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacorrienteproveedor',
            name='id',
        ),
        migrations.AlterField(
            model_name='cuentacorrienteproveedor',
            name='numero_cuenta',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número de cuenta'),
        ),
    ]
