# Generated by Django 3.1.7 on 2021-06-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20210620_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opciones', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=8)),
            ],
        ),
    ]
