# Generated by Django 3.1.7 on 2021-05-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20210514_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.IntegerField(unique=True, verbose_name='Cuit'),
        ),
    ]
