# Generated by Django 3.1.7 on 2021-06-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_proveedor_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuentaCorriente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opciones', models.CharField(choices=[('ACTIVA', 'Activo'), ('INACTIVA', 'Inactiva')], max_length=8)),
            ],
        ),
    ]
