# Generated by Django 3.1.7 on 2021-06-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0005_estadocuentacorriente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuentacorriente',
            name='opciones',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], max_length=8),
        ),
    ]
