# Generated by Django 3.1.7 on 2021-06-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0006_auto_20210621_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='proveedor.estadocuentacorriente'),
            preserve_default=False,
        ),
    ]
