# Generated by Django 3.1.7 on 2021-05-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opciones', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('responsable_inscripto', models.BooleanField(blank=True, default=False, null=True, verbose_name='Responsable Inscripto')),
                ('total', models.IntegerField(null=True, verbose_name='Total del presupuesto')),
                ('comentarios', models.CharField(blank=True, max_length=45, null=True, verbose_name='Comentarios')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.estadopresupuesto')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal')),
            ],
        ),
    ]
