# Generated by Django 3.1.7 on 2021-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='comentarios',
            field=models.CharField(max_length=45, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_expiracion',
            field=models.DateTimeField(verbose_name='Fecha de expiración'),
        ),
    ]
