# Generated by Django 3.1.7 on 2021-05-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='items',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuario.vendedor'),
            preserve_default=False,
        ),
    ]
