# Generated by Django 3.1.7 on 2021-06-23 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_auto_20210618_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='comentarios',
        ),
    ]
