# Generated by Django 3.1.7 on 2021-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_auto_20210522_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='comentarios',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Comentarios'),
        ),
    ]
