# Generated by Django 3.1.7 on 2021-05-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210526_1744'),
        ('sucursal', '0001_initial'),
        ('presupuesto', '0002_auto_20210526_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('cantidad_solicitada', models.IntegerField(default=0, null=True, verbose_name='Cantidad solicitada')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('presupuesto_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuesto.presupuesto')),
                ('sucursal_asociada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal')),
            ],
            options={
                'verbose_name': 'item de venta',
                'verbose_name_plural': 'items de ventas',
            },
        ),
    ]
