# Generated by Django 3.1.7 on 2021-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_itempresupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopresupuesto',
            name='opciones',
            field=models.CharField(choices=[('EN EVALUACION', 'En Evaluacion'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=13),
        ),
    ]
