# Generated by Django 3.1.7 on 2021-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_auto_20210522_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='responsable_inscripto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Responsable Inscripto'),
        ),
    ]
