# Generated by Django 3.1.7 on 2021-05-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_auto_20210526_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='sucursal',
            new_name='sucursal_asociada',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='vendedor',
            new_name='vendedor_asociado',
        ),
    ]
