# Generated by Django 3.1.7 on 2021-06-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_deuda_numero_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deuda',
            old_name='cliete_asociado',
            new_name='cliente_asociado',
        ),
    ]
