# Generated by Django 3.1.7 on 2021-06-21 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_estadocuentacorriente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.estadocuentacorriente'),
            preserve_default=False,
        ),
    ]
