# Generated by Django 3.1.7 on 2021-06-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20210607_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodemoneda',
            name='opciones',
            field=models.CharField(choices=[('EURO', 'Euro'), ('DOLAR', 'Dolar'), ('PESO', 'Peso')], max_length=5),
        ),
    ]
