# Generated by Django 3.1.7 on 2021-05-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Provincia'),
        ),
    ]
