# Generated by Django 3.1.7 on 2021-05-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name': 'supervisor', 'verbose_name_plural': 'supervisores'},
        ),
    ]
