# Generated by Django 3.1.7 on 2021-06-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado',
            new_name='EstadoUsuario',
        ),
    ]
