# Generated by Django 3.1.7 on 2021-05-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20210514_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cod_postal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cuit',
            field=models.IntegerField(unique=True, verbose_name='Cuit'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
