# Generated by Django 3.1.7 on 2021-05-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponible', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Saldo Disponible')),
                ('egresos', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Egresos')),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ingresos')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Saldo Inicial')),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Saldo Final')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=50, null=True, unique=True)),
                ('idCasaCentral', models.IntegerField(default=1)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sucursal.caja')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
            },
        ),
    ]
