# Generated by Django 3.1.7 on 2021-05-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='direccion',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='calle',
            field=models.CharField(max_length=20, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='cod_postal',
            field=models.IntegerField(null=True, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='localidad',
            field=models.CharField(max_length=20, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='provincia',
            field=models.CharField(max_length=20, null=True, verbose_name='Provincia'),
        ),
    ]
