# Generated by Django 3.1.7 on 2021-06-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='ingresos',
        ),
        migrations.AddField(
            model_name='caja',
            name='ingresos_en_dolares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Ingresos en dolares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='ingresos_en_euros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Ingresos en euros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='ingresos_en_pesos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Ingresos en pesos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='saldo_disponible_dolares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Saldo disponible en dolares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='saldo_disponible_euros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Saldo disponible en euros'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Saldo disponible en pesos'),
        ),
    ]
