# Generated by Django 3.1.7 on 2021-05-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'verbose_name': 'caja', 'verbose_name_plural': 'cajas'},
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
