# Generated by Django 3.1.7 on 2021-05-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0002_auto_20210515_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='codigo',
            field=models.CharField(max_length=4, null=True, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sucursal.caja', unique=True),
        ),
    ]
