# Generated by Django 3.1.7 on 2021-06-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0002_auto_20210618_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='identificador',
            field=models.CharField(max_length=50, verbose_name='Identificador'),
        ),
    ]
