# Generated by Django 3.1.7 on 2021-05-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0002_auto_20210518_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='caja_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucursal.caja'),
        ),
    ]
