# Generated by Django 3.1.7 on 2021-05-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0003_auto_20210516_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='caja',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='sucursal.caja'),
        ),
    ]
