# Generated by Django 3.1.7 on 2021-05-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0004_auto_20210516_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='codigo',
            field=models.CharField(default='', max_length=4, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='caja',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='sucursal.caja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='calle',
            field=models.CharField(default='', max_length=20, verbose_name='Calle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='cod_postal',
            field=models.CharField(default='', max_length=4, verbose_name='Código postal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='numero',
            field=models.CharField(default='', max_length=4, verbose_name='Numero'),
            preserve_default=False,
        ),
    ]
