# Generated by Django 3.1.7 on 2021-05-22 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0001_initial'),
        ('item', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoVentaVirtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opciones', models.CharField(choices=[('CANCELADO POR EL CLIENTE', 'Cancelada Por Cliente'), ('CANCELADO POR LA SUCURSAL', 'Cancelada Por Sucursal'), ('PENDIENTE', 'Pendiente'), ('EN PREPARACIÓN', 'En Preparacion'), ('LISTA', 'Lista'), ('RETIRADA', 'Retirada'), ('RECHAZADA', 'Rechazada')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('numero_comprobante', models.CharField(max_length=25, unique=True, verbose_name='Número de comprobrante')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('cantidad_solicitada', models.IntegerField(default=0, null=True, verbose_name='Cantidad solicitada')),
                ('cliente_asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente')),
                ('cuenta_corriente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cuentacorriente')),
                ('item_asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
                ('mediodepago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.mediodepago')),
                ('sucursal_asociada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal')),
                ('vendedor_asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='VentaLocal',
            fields=[
                ('venta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='venta.venta')),
            ],
            options={
                'verbose_name': 'venta-local',
                'verbose_name_plural': 'ventas-locales',
            },
            bases=('venta.venta',),
        ),
        migrations.CreateModel(
            name='VentaVirtual',
            fields=[
                ('venta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='venta.venta')),
                ('comentarios', models.CharField(blank=True, max_length=50, null=True, verbose_name='Comentarios')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.estadoventavirtual')),
            ],
            options={
                'verbose_name': 'venta-virtual',
                'verbose_name_plural': 'ventas-virtuales',
            },
            bases=('venta.venta',),
        ),
    ]
