# Generated by Django 3.1.7 on 2021-06-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('numero_venta', models.IntegerField(verbose_name='N° de venta')),
                ('pago', models.CharField(max_length=30, verbose_name='Método de pago')),
                ('vendedor', models.CharField(max_length=30, verbose_name='Vendedor Asociado')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total de la compra')),
            ],
            options={
                'verbose_name': 'comprobante de pago',
                'verbose_name_plural': 'comprobantes de pago',
            },
        ),
    ]
