# Generated by Django 3.1.7 on 2021-05-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210522_0530'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='vendedor_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.vendedor'),
        ),
    ]
