# Generated by Django 3.1.7 on 2021-06-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_ingresado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto del cliente'),
        ),
    ]
