# Generated by Django 3.1.7 on 2021-06-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_comprobantepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepago',
            name='total',
            field=models.CharField(max_length=30, verbose_name='Total de la compra'),
        ),
    ]
