# Generated by Django 3.1.7 on 2021-06-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_venta_monto_ingresado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoventa',
            name='opciones',
            field=models.CharField(choices=[('CANCELADA POR EL CLIENTE', 'Cancelada Por Cliente'), ('CANCELADA POR LA SUCURSAL', 'Cancelada Por Sucursal'), ('PENDIENTE DE RETIRO', 'Pendiente De Retiro'), ('EN PREPARACION', 'En Preparacion'), ('LISTA', 'Lista'), ('PAGADA', 'Pagada'), ('EN DEUDA', 'En Deuda'), ('RETIRADA', 'Retirada'), ('RECHAZADA', 'Rechazada'), ('NO RETIRADA', 'No Retirado')], max_length=25),
        ),
    ]
