# Generated by Django 3.1.7 on 2021-06-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20210607_2316'),
        ('venta', '0003_auto_20210607_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('cotizacion', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cotización')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.tipodemoneda')),
            ],
            options={
                'verbose_name': 'cotizacion',
                'verbose_name_plural': 'cotizaciones',
            },
        ),
    ]
