# Generated by Django 3.1.7 on 2021-06-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20210616_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobantepago',
            old_name='pago',
            new_name='mediodepago',
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='moneda',
            field=models.CharField(default=1, max_length=30, verbose_name='Tipo de moneda'),
            preserve_default=False,
        ),
    ]
