# Generated by Django 3.1.7 on 2021-06-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20210616_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantepago',
            name='sucursal',
            field=models.CharField(default=1, max_length=30, verbose_name='Sucursal Asociada'),
            preserve_default=False,
        ),
    ]
