# Generated by Django 3.1.7 on 2021-06-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_cotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='total',
            new_name='total_dolar',
        ),
        migrations.AddField(
            model_name='venta',
            name='total_euro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
