# Generated by Django 3.1.7 on 2021-06-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20210608_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total_dolar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total en dolares'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_euro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total en euros'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total en pesos'),
        ),
    ]
