from django.urls import path
from .views import ListadoItem, EliminarMezcla, RegistrarItem, EditarItem,ReporteItemsStockFaltante, CambiarEstadoItem, ConfigurarReposicionItem, ListarCategorias, ListarPedidos,  VerPedido, RecibirStock, MensajeExitoso, ModificarCampos, CambioMasivo, ListarPintura, AgregarPintura, ListadoPinturaUsada, IniciarMezcla, mezclarPinturas, ListadoMezclas, ListadoPinturaNueva, ListadoMezclaUsada, IniciarMezclaUsada, mezclarPinturasUsadas, EliminarMezclaUsada, ReporteItemRiesgoStock, ReporteCambiosPrecios, ReporteCuentaCorrienteProveedores, CambioMasivoItems, ModificarCamposItems, AsignarProveedor, ordenarItemPorNombre, ordenarPorStockMinimo, ordenarPorStockSeguridad, HistorialPreferenciados, SolicitarStock, RealizarPedido
from django.contrib.auth.decorators import login_required

urlpatterns = [

    path('listado_items/', login_required(ListadoItem.as_view()), name='listar_items'),
    path('registrar_item/', login_required(RegistrarItem.as_view()),
         name='registrar_item'),
    path('actualizar_item/<int:pk>/',
         login_required(EditarItem.as_view()), name='actualizar_item'),
    path('cambiar_estado/<int:pk>/',
         login_required(CambiarEstadoItem.as_view()), name='cambiar_estado'),
    path('reposicion_item/<int:pk>/',
         login_required(ConfigurarReposicionItem.as_view()), name='reposicion_item'),
    path('listar_categorias/', login_required(ListarCategorias.as_view()),
         name='listar_categorias'),
    path('listar_categorias/AsignarProveedor/',
         login_required(AsignarProveedor), name='asignar_proveedor'),
    path('visualizar_pedidos/', login_required(ListarPedidos.as_view()),
         name='visualizar_pedidos'),
    path('pedido_proveedor/<int:id_proveedor>/<int:id_sucursal>/',
         VerPedido, name='pedido_proveedor'),
    path('pedido_proveedor/<int:id_proveedor>/<int:id_sucursal>/RecibirStock/',
         RecibirStock, name='pedido_proveedor'),
    path('stock_recibido/', MensajeExitoso.as_view(), name='stock_recibido'),
    path('ver_categorias/', ModificarCampos.as_view(), name='ver_categorias'),
    path('ver_categorias/CambioMasivo/', CambioMasivo, name='cambio_masivo'),
    path('listar_pinturas/', login_required(ListarPintura),
         name='listar_pinturas'),
    path('registrar_pintura/', login_required(AgregarPintura.as_view()),
         name='registrar_pintura'),
    path('listar_pinturas_nuevas/', login_required(ListadoPinturaNueva.as_view()),
         name='listar_pinturas_nuevas'),
    path('listar_pinturas_usadas/', login_required(ListadoPinturaUsada.as_view()),
         name='listar_pinturas_usadas'),
    path('iniciar_mezcla/', login_required(IniciarMezcla.as_view()),
         name='iniciar_mezcla'),
    path('finalizar_mezcla/<int:mezcla>/<int:primerapintura>/<int:segundapintura>/<int:cantidad_primera>/<int:cantidad_segunda>/',
         login_required(mezclarPinturas), name='finalizar_mezcla'),
    path('listar_mezclas/', login_required(ListadoMezclas.as_view()),
         name='listar_mezclas'),
    path('eliminar_mezcla/<int:pk>/',
         login_required(EliminarMezcla.as_view()), name='eliminar_mezcla'),
    path('iniciar_mezcla_usada/', login_required(IniciarMezclaUsada.as_view()),
         name='iniciar_mezcla_usada'),
    path('finalizar_mezcla_usada/<int:mezcla>/<int:primerapintura>/<int:segundapintura>/<int:cantidad_primera>/<int:cantidad_segunda>/',
         login_required(mezclarPinturasUsadas), name='finalizar_mezcla_usada'),
    path('listar_mezclas_usadas/', login_required(ListadoMezclaUsada.as_view()),
         name='listar_mezclas_usadas'),
    path('eliminar_mezcla_usada/<int:pk>/',
         login_required(EliminarMezclaUsada.as_view()), name='eliminar_mezcla_usada'),
    path('reporte_riesgo_stock/', login_required(ReporteItemRiesgoStock),
         name='reporte_riesgo_stock'),
    path('reporte_cambios_masivos/', login_required(ReporteCambiosPrecios),
         name='reporte_cambios_masivos'),
    path('reporte_cuenta_corriente_proveedores/', login_required(
        ReporteCuentaCorrienteProveedores), name='reporte_cuenta_corriente_proveedores'),
    path('ver_items/', ModificarCamposItems.as_view(), name='ver_items'),
    path('ver_items/CambioMasivoItems/',
         CambioMasivoItems, name='cambio_masivo_items'),
    path('listar_item_nombre/', login_required(ordenarItemPorNombre),
         name='listar_item_nombre'),
    path('listar_item_stockminimo/', login_required(ordenarPorStockMinimo),
         name='listar_item_stockminimo'),
    path('listar_item_stockseguridad/', login_required(ordenarPorStockSeguridad),
         name='listar_item_stockseguridad'),
    path('historial_preferenciados/', login_required(HistorialPreferenciados.as_view()),
         name='historial_preferenciados'),
    path('solicitar_stock/<int:item>/', login_required(SolicitarStock), name= 'solicitar_stock'),
    path('solicitar_stock/<int:item>/RealizarPedido/', login_required(RealizarPedido), name = 'realizar_pedido'),
    path('reporte_stock_faltante/', login_required(ReporteItemsStockFaltante),  name='reporte_stock_faltante'),

]
