# Generated by Django 2.2.3 on 2021-05-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrarSucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
