# Generated by Django 2.2.3 on 2021-05-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrarSucursales', '0002_auto_20210509_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuit', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
    ]
