# Generated by Django 3.1.7 on 2021-05-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opciones', models.CharField(choices=[('DÉBITO', 'Debito'), ('CRÉDITO', 'Credito'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADOPAGO', 'Mercadopago'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mediodepago.tipodepago')),
            ],
            options={
                'verbose_name': 'mediodepago',
                'verbose_name_plural': 'mediosdepago',
            },
        ),
    ]
